# Generated by Django 5.2.3 on 2025-06-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('pl', 'Polski'), ('ua', 'Ukraiński')], max_length=2)),
                ('type', models.CharField(choices=[('skojarzenie', 'Skojarzenie'), ('definicja', 'Definicja')], max_length=15)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name', 'value', 'language', 'type')},
            },
        ),
        migrations.CreateModel(
            name='AnswerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.answer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.tag')),
            ],
            options={
                'unique_together': {('answer', 'tag')},
            },
        ),
    ]
