# Generated by Django 5.2.3 on 2025-06-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('określenie', 'Określenie'), ('obiekt', 'Obiekt'), ('pojęcie', 'Pojęcie'), ('doznanie', 'Doznanie'), ('działanie', 'Działanie'), ('atrybut', 'Atrybut')], default='pojęcie', max_length=20),
        ),
        migrations.AlterField(
            model_name='answertag',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answertag', to='surveys.answer'),
        ),
    ]
