# Generated by Django 5.2.3 on 2025-06-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_tag_category_alter_answertag_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('definition', 'Określenie'), ('object', 'Obiekt'), ('notion', 'Pojęcie'), ('experience', 'Doznanie'), ('action', 'Działanie'), ('attributes', 'Atrybut')], default='pojęcie', max_length=20),
        ),
    ]
